// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int cli_Id { get; set; }
        public string cli_Nombres { get; set; }
        public string cli_Apellidos { get; set; }
        public string cli_Identidad { get; set; }
        public string cli_Sexo { get; set; }
        public string mun_Id { get; set; }
        public string cli_DireccionExacta { get; set; }
        public string cli_Telefono { get; set; }
        public string cli_CorreoElectronico { get; set; }
        public int cli_UsuCreacion { get; set; }
        public DateTime cli_FechaCreacion { get; set; }
        public int? cli_UsuModificacion { get; set; }
        public DateTime? cli_FechaModificacion { get; set; }
        public bool? cli_Estado { get; set; }

        public virtual tbUsuarios cli_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios cli_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}