// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string dep_Id { get; set; }
        public string dep_Nombre { get; set; }
        public int dep_UsuCreacion { get; set; }
        public DateTime dep_FechaCreacion { get; set; }
        public int? dep_UsuModificacion { get; set; }
        public DateTime? dep_FechaModificacion { get; set; }
        public bool dep_Estado { get; set; }

        public virtual tbUsuarios dep_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios dep_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}