// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbFacturas = new HashSet<tbFacturas>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }
        [Display(Name = "ID")]
        public int empe_Id { get; set; }
        [Display(Name = "Nombres")]
        public string empe_Nombres { get; set; }
        [Display(Name = "Apellidos")]
        public string empe_Apellidos { get; set; }
        [Display(Name = "Identidad")]
        public string empe_Identidad { get; set; }
        [Display(Name = "Fecha Nacimiento")]
        public DateTime empe_FechaNacimiento { get; set; }
        [Display(Name = "Sexo")]
        public string empe_Sexo { get; set; }
        [Display(Name = "Estado Civil")]
        public int estacivi_Id { get; set; }
        [Display(Name = "Municipio")]
        public string muni_Id { get; set; }
        [Display(Name = "Direccion")]
        public string empe_Direccion { get; set; }
        [Display(Name = "Telefono")]
        public string empe_Telefono { get; set; }
        [Display(Name = "Correo Electronico")]
        public string empe_CorreoElectronico { get; set; }
        [Display(Name = "Sucursal")]
        public int sucu_Id { get; set; }
        [Display(Name = "Usuario Creacion")]
        public int empe_UsuCreacion { get; set; }
        [Display(Name = "Fecha Creacion")]
        public DateTime empe_FechaCreacion { get; set; }
        [Display(Name = "Usuario Modificacion")]
        public int? empe_UsuModificacion { get; set; }
        [Display(Name = "Fecha Modificacion")]
        public DateTime? empe_FechaModificacion { get; set; }
        [Display(Name = "Estado")]
        public bool? empe_Estado { get; set; }

        public virtual tbUsuarios empe_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios empe_UsuModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles estacivi { get; set; }
        public virtual tbMunicipios depa_Id { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}