// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int emp_Id { get; set; }
        public string emp_Nombres { get; set; }
        public string emp_Apellidos { get; set; }
        public string emp_Identidad { get; set; }
        public DateTime emp_FechaNacimiento { get; set; }
        public string emp_Sexo { get; set; }
        public int estciv_Id { get; set; }
        public string mun_Id { get; set; }
        public string emp_Direccion { get; set; }
        public string emp_Telefono { get; set; }
        public string emp_CorreoElectronico { get; set; }
        public int emp_UsuCreacion { get; set; }
        public DateTime emp_FechaCreacion { get; set; }
        public int? emp_UsuModificacion { get; set; }
        public DateTime? emp_FechaModificacion { get; set; }
        public bool? emp_Estado { get; set; }

        public virtual tbUsuarios emp_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios emp_UsuModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles estciv { get; set; }
        public virtual tbMunicipios mun { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}