// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int estciv_Id { get; set; }
        public string estciv_Nombre { get; set; }
        public int estciv_UsuCreacion { get; set; }
        public DateTime estciv_FechaCreacion { get; set; }
        public int? estciv_UsuModificacion { get; set; }
        public DateTime? estciv_FechaModificacion { get; set; }
        public bool estciv_Estado { get; set; }

        public virtual tbUsuarios estciv_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios estciv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}