// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
        }

        public int fact_Id { get; set; }
        public int clie_Id { get; set; }
        public DateTime fact_Fecha { get; set; }
        public int meto_Id { get; set; }
        public int empe_Id { get; set; }
        public int fact_UsuCreacion { get; set; }
        public DateTime fact_FechaCreacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public int? fact_UsuModificacion { get; set; }
        public bool? fact_Estado { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual tbUsuarios fact_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios fact_UsuModificacionNavigation { get; set; }
        public virtual tbMetodosPago meto { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
    }
}