// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tblEmpleados
    {
        public int EmpleadoId { get; set; }
        public string EmpleadoNombre { get; set; }
        public string EmpleadoApelldio { get; set; }
        public string EmpleadoTelefono { get; set; }
        public string EmpleadoDireccion { get; set; }
    }
}