// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int met_Id { get; set; }
        public string met_Nombre { get; set; }
        public int met_UsuCreacion { get; set; }
        public DateTime met_FechaCreacion { get; set; }
        public int? met_UsuModificacion { get; set; }
        public DateTime? met_FechaModificacion { get; set; }
        public bool met_Estado { get; set; }

        public virtual tbUsuarios met_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios met_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}