// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public string mun_id { get; set; }
        public string mun_Nombre { get; set; }
        public string dep_Id { get; set; }
        public int mun_UsuCreacion { get; set; }
        public DateTime mun_FechaCreacion { get; set; }
        public int? mun_UsuModificacion { get; set; }
        public DateTime? mun_FechaModificacion { get; set; }
        public bool mun_Estado { get; set; }

        public virtual tbDepartamentos dep { get; set; }
        public virtual tbUsuarios mun_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios mun_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}