// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int pantrole_Id { get; set; }
        public string pantrole_Identificador { get; set; }
        public int role_Id { get; set; }
        public int pant_Id { get; set; }
        public int pantrole_UsuCreacion { get; set; }
        public DateTime pantrole_FechaCreacion { get; set; }
        public int? pantrole_UsuModificacion { get; set; }
        public DateTime? pantrole_FechaModificacion { get; set; }
        public bool? pantrole_Estado { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbUsuarios pantrole_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios pantrole_UsuModificacionNavigation { get; set; }
        public virtual tbRoles role { get; set; }
    }
}