// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int pantrol_Id { get; set; }
        public string pantrol_Identificador { get; set; }
        public int rol_Id { get; set; }
        public int pant_Id { get; set; }
        public int pantrol_UsuCreacion { get; set; }
        public DateTime pantrol_FechaCreacion { get; set; }
        public int? pantrol_UsuModificacion { get; set; }
        public DateTime? pantrol_FechaModificacion { get; set; }
        public bool pantrol_Estado { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbRoles rol { get; set; }
    }
}