// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbProductos
    {
        public int prod_Id { get; set; }
        public string prod_Nombre { get; set; }
        public decimal prod_PrecioUni { get; set; }
        public int cate_Id { get; set; }
        public int prov_Id { get; set; }
        public int prod_Stock { get; set; }
        public int prod_UsuCreacion { get; set; }
        public DateTime prod_FechaCreacion { get; set; }
        public DateTime? prod_FechaModificacion { get; set; }
        public int? prod_UsuModificacion { get; set; }
        public bool? prod_Estado { get; set; }

        public virtual tbCategorias cate { get; set; }
        public virtual tbUsuarios prod_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios prod_UsuModificacionNavigation { get; set; }
        public virtual tbProveedores prov { get; set; }
    }
}