// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbProductos
    {
        public int pro_Id { get; set; }
        public string pro_Nombre { get; set; }
        public decimal pro_PrecioUni { get; set; }
        public int cat_Id { get; set; }
        public int prov_Id { get; set; }
        public int pro_Stock { get; set; }
        public int pro_UsuCreacion { get; set; }
        public DateTime pro_FechaCreacion { get; set; }
        public DateTime? pro_FechaModificacion { get; set; }
        public int? pro_UsuModificacion { get; set; }
        public bool pro_Estado { get; set; }

        public virtual tbCategorias cat { get; set; }
        public virtual tbUsuarios pro_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios pro_UsuModificacionNavigation { get; set; }
        public virtual tbProveedores prov { get; set; }
    }
}