// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int rol_Id { get; set; }
        public string rol_Nombre { get; set; }
        public int rol_UsuCreacion { get; set; }
        public DateTime rol_FechaCreacion { get; set; }
        public int? rol_UsuModificacion { get; set; }
        public DateTime? rol_FechaModificacion { get; set; }
        public bool rol_Estado { get; set; }

        public virtual tbUsuarios rol_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios rol_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}