// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusu_UsuCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusu_UsuModificacionNavigation = new HashSet<tbUsuarios>();
            tbCategoriascat_UsuCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriascat_UsuModificacionNavigation = new HashSet<tbCategorias>();
            tbClientescli_UsuCreacionNavigation = new HashSet<tbClientes>();
            tbClientescli_UsuModificacionNavigation = new HashSet<tbClientes>();
            tbDepartamentosdep_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdep_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosemp_UsuCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosemp_UsuModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesestciv_UsuCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestciv_UsuModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturasDetallesfacdet_UsuCreacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasDetallesfacdet_UsuModificacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasfac_UsuCreacionNavigation = new HashSet<tbFacturas>();
            tbFacturasfac_UsuModificacionNavigation = new HashSet<tbFacturas>();
            tbMetodosPagomet_UsuCreacionNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagomet_UsuModificacionNavigation = new HashSet<tbMetodosPago>();
            tbMunicipiosmun_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmun_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbProductospro_UsuCreacionNavigation = new HashSet<tbProductos>();
            tbProductospro_UsuModificacionNavigation = new HashSet<tbProductos>();
            tbProveedoresprov_UsuCreacionNavigation = new HashSet<tbProveedores>();
            tbProveedoresprov_UsuModificacionNavigation = new HashSet<tbProveedores>();
            tbRolesrol_UsuCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrol_UsuModificacionNavigation = new HashSet<tbRoles>();
        }

        public int usu_id { get; set; }
        public string usu_NombreUsuario { get; set; }
        public string usu_Contrasena { get; set; }
        public bool? usu_EsAdmin { get; set; }
        public int? rol_Id { get; set; }
        public int? emp_Id { get; set; }
        public int? usu_UsuCreacion { get; set; }
        public DateTime usu_FechaCreacion { get; set; }
        public int? usu_UsuModificacion { get; set; }
        public DateTime? usu_FechaModificacion { get; set; }
        public bool usu_Estado { get; set; }

        public virtual tbEmpleados emp { get; set; }
        public virtual tbRoles rol { get; set; }
        public virtual tbUsuarios usu_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios usu_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusu_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascat_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascat_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientescli_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientescli_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdep_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdep_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosemp_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosemp_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestciv_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestciv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfacdet_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfacdet_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfac_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfac_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagomet_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagomet_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmun_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmun_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductospro_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductospro_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrol_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrol_UsuModificacionNavigation { get; set; }
    }
}