// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_gral_tbMunicipios_VW
    {
        public string muni_id { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int muni_UsuCreacion { get; set; }
        public string muni_UsuCreacion_Nombre { get; set; }
        public DateTime muni_FechaCreacion { get; set; }
        public int? muni_UsuModificacion { get; set; }
        public string muni_UsuModificacion_Nombre { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool muni_Estado { get; set; }
    }
}