// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_gral_tbEstadosCiviles_VW
    {
        public int estacivi_Id { get; set; }
        public string estacivi_Nombre { get; set; }
        public int estacivi_UsuCreacion { get; set; }
        public string estacivi_UsuCreacion_Nombre { get; set; }
        public DateTime estacivi_FechaCreacion { get; set; }
        public int? estacivi_UsuModificacion { get; set; }
        public string estacivi_UsuModificacion_Nombre { get; set; }
        public DateTime? estacivi_FechaModificacion { get; set; }
        public bool estacivi_Estado { get; set; }
    }
}