// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_gral_tbDepartamentos_VW
    {
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int depa_UsuCreacion { get; set; }
        public string depe_UsuCreacion_Nombre { get; set; }
        public DateTime depa_FechaCreacion { get; set; }
        public int? depa_UsuModificacion { get; set; }
        public string depa_UsuModificacion_Nombre { get; set; }
        public DateTime? depa_FechaModificacion { get; set; }
        public bool depa_Estado { get; set; }
    }
}