// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbSucursales_VW
    {
        [Display(Name = "ID")]
        public int sucu_Id { get; set; }
        [Display(Name = "Sucursal")]
        public string sucu_Descripcion { get; set; }
        [Display(Name = "Direccion Exacta")]
        public string sucu_DireccionExacta { get; set; }
        [Display(Name = "Fecha Creacion")]
        public DateTime sucu_FechaCreacion { get; set; }
        [Display(Name = "Usuario Creacion ID")]
        public int sucu_UsuCreacion { get; set; }
        [Display(Name = "Fecha Modificacion")]
        public DateTime? sucu_FechaModificacion { get; set; }
        [Display(Name = "Usuario Modificacion ID")]
        public int? sucu_UsuModificacion { get; set; }
        [Display(Name = "Estado")]
        public bool sucu_Estado { get; set; }
        [Display(Name = "Departamento ID")]
        public string depa_Id { get; set; }
        [Display(Name = "Departamento")]
        public string depa_Nombre { get; set; }
        [Display(Name = "Municipio ID")]
        public string muni_Id { get; set; }
        [Display(Name = "Municipio")]
        public string muni_Nombre { get; set; }
        [Display(Name = "Usuario Creacion")]
        public string sucu_UsuCreacion_Nombre { get; set; }
        [Display(Name = "Usuario Modificacion")]
        public string sucu_UsuModificacion_Nombre { get; set; }
    }
}