// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbMetodosPago_View
    {
        public int meto_Id { get; set; }
        public string meto_Nombre { get; set; }
        public int meto_UsuCreacion { get; set; }
        public string meto_UsuCreacion_Nombre { get; set; }
        public DateTime meto_FechaCreacion { get; set; }
        public int? meto_UsuModificacion { get; set; }
        public string meto_UsuModificacion_Nombre { get; set; }
        public DateTime? meto_FechaModificacion { get; set; }
        public bool meto_Estado { get; set; }
    }
}