// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbProductos_VW
    {
        [Display(Name = "ID")]
        public int prod_Id { get; set; }

        [Display(Name = "Nombre")]
        public string prod_Nombre { get; set; }

        [Display(Name = "Precio unitario")]
        public decimal prod_PrecioUni { get; set; }

        public int cate_Id { get; set; }

        [Display(Name = "Categoría")]
        public string cate_Nombre { get; set; }
        public int prov_Id { get; set; }

        [Display(Name = "Proveedor")]
        public string prov_Nombre { get; set; }

        [Display(Name = "Stock")]
        public int prod_Stock { get; set; }
        public int prod_UsuCreacion { get; set; }
        public string user_UsuCreacion_Nombre { get; set; }
        public DateTime prod_FechaCreacion { get; set; }
        public DateTime? prod_FechaModificacion { get; set; }
        public int? prod_UsuModificacion { get; set; }
        public string user_UsuModificacion_Nombre { get; set; }
        public bool prod_Estado { get; set; }
    }
}