// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbCategorias_VW
    {
        [Display(Name = "ID")]
        public int cate_Id { get; set; }

        [Display(Name = "Nombre")]
        public string cate_Nombre { get; set; }

        [Display(Name = "Usuario Creación ID")]
        public int cate_UsuCreacion { get; set; }

        [Display(Name = "Usuario Creación")]
        public string cate_UsuCreacion_Nombre { get; set; }

        [Display(Name = "Fecha Creación")]
        public DateTime cate_FechaCreacion { get; set; }

        [Display(Name = "Usuario Modificación ID")]
        public int? cate_UsuModificacion { get; set; }

        [Display(Name = "Usuario Modificación")]
        public string cate_UsuModificacion_Nombre { get; set; }

        [Display(Name = "Fecha Modificación")]
        public DateTime? cate_FechaModificacion { get; set; }
        public bool cate_Estado { get; set; }
    }
}