// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbClientes_DDLMunicipios
    {
        public string muni_Nombre { get; set; }
        public string muni_id { get; set; }
        public int clie_Id { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
    }
}