// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbCategorias_VW
    {
        public int cate_Id { get; set; }
        public string cate_Nombre { get; set; }
        public int cate_UsuCreacion { get; set; }
        public string cate_UsuCreacion_Nombre { get; set; }
        public DateTime cate_FechaCreacion { get; set; }
        public int? cate_UsuModificacion { get; set; }
        public string cate_UsuModificacion_Nombre { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }
        public bool cate_Estado { get; set; }
    }
}