// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbProveedores_VW
    {
        [Display(Name = "ID")]
        public int prov_Id { get; set; }
        [Display(Name = "Proveedor")]
        public string prov_Nombre { get; set; }
        [Display(Name = "CorreoElectronico")]
        public string prov_CorreoElectronico { get; set; }
        [Display(Name = "Telefono")]
        public string prov_Telefono { get; set; }
        [Display(Name = "Usuario Creacion ID")]
        public int prov_UsuCreacion { get; set; }
        [Display(Name = "Usuario Creacion")]
        public string prov_UsuCreacion_Nombre { get; set; }
        [Display(Name = "Fecha Creacion")]
        public DateTime prov_FechaCreacion { get; set; }
        [Display(Name = "Usuario Modificacion ID")]
        public int? prov_UsuModificacion { get; set; }
        [Display(Name = "Usuario Modificacion")]
        public string prov_UsuModificacion_Nombre { get; set; }
        [Display(Name = "Fecha Modificacion")]
        public DateTime? prov_FechaModificacion { get; set; }
        [Display(Name = "Estado")]
        public bool prov_Estado { get; set; }
    }
}