// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbClientes_VW
    {
        public int clie_Id { get; set; }
        public string clie_NombreCompleto { get; set; }
        public string clie_Identidad { get; set; }
        public string clie_Sexo { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string clie_DireccionExacta { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int clie_UsuCreacion { get; set; }
        public string clie_UsuCreacion_Nombre { get; set; }
        public int? clie_UsuModificacion { get; set; }
        public int? clie_UsuModificacion_Nombre { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
    }
}