// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbProductos_VW
    {
        [Display(Name = "ID")]
        public int prod_Id { get; set; }
        [Display(Name = "Producto")]
        public string prod_Nombre { get; set; }
        [Display(Name = "Precio Unitario")]
        public decimal prod_PrecioUni { get; set; }
        [Display(Name = "Categoria ID")]
        public int cate_Id { get; set; }
        [Display(Name = "Categoria")]
        public string cate_Nombre { get; set; }
        [Display(Name = "Proveedor ID")]
        public int prov_Id { get; set; }
        [Display(Name = "Proveedor")]
        public string prov_Nombre { get; set; }
        [Display(Name = "Stock")]
        public int prod_Stock { get; set; }
        [Display(Name = "Usuario Creacion ID")]
        public int prod_UsuCreacion { get; set; }
        [Display(Name = "Usuario Creacion")]
        public string user_UsuCreacion_Nombre { get; set; }
        [Display(Name = "Fecha Creacion")]
        public DateTime prod_FechaCreacion { get; set; }
        [Display(Name = "Fecha Modificacion")]
        public DateTime? prod_FechaModificacion { get; set; }
        [Display(Name = "Usuario Modificacion ID")]
        public int? prod_UsuModificacion { get; set; }
        [Display(Name = "Usuario Modificacion")]
        public string user_UsuModificacion_Nombre { get; set; }
        [Display(Name = "Estado")]
        public bool prod_Estado { get; set; }
    }
}