// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbEmpleados_View
    {
        public int empe_Id { get; set; }
        public string NombreCompleto { get; set; }
    }
}