// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_maqu_tbEmpleados_View
    {
        public int empe_Id { get; set; }
        public string NombreCompleto { get; set; }
        public string empe_Nombres { get; set; }
        public string empe_Apellidos { get; set; }
        public string empe_Identidad { get; set; }
        public DateTime empe_FechaNacimiento { get; set; }
        public string empe_Sexo { get; set; }
        public int estacivi_Id { get; set; }
        public string estacivi_Nombre { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public int sucu_Id { get; set; }
        public string sucu_Descripcion { get; set; }
        public string empe_Direccion { get; set; }
        public string empe_Telefono { get; set; }
        public string empe_CorreoElectronico { get; set; }
        public int empe_UsuCreacion { get; set; }
        public string user_NombreUsuario { get; set; }
        public string empe_UsuModificacion { get; set; }
        public DateTime empe_FechaCreacion { get; set; }
        public DateTime? empe_FechaModificacion { get; set; }
    }
}