// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbFacturas_List
    {
        [Display(Name = "ID")]
        public int fact_Id { get; set; }

        [Display(Name = "Cliente")]
        public string clie_Nombres { get; set; }

        [Display(Name = "Empleado")]
        public string empe_Nombres { get; set; }

        [Display(Name = "Método de Pago")]
        public string meto_Nombre { get; set; }

        [Display(Name = "Fecha")]
        public DateTime fact_Fecha { get; set; }
    }
}