// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbFacturasDetalles_List
    {
        public int factdeta_Id { get; set; }
        public int fact_Id { get; set; }
        public string prod_Nombre { get; set; }
        public int factdeta_Cantidad { get; set; }
        public decimal factdeta_Precio { get; set; }
        public decimal? factdeta_PrecioTotal { get; set; }
    }
}