// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbFacturas_List
    {
        [Display(Name = "ID")]
        public int fact_Id { get; set; }

        [Display(Name = "Nombre Cliente")]
        public string clie_Nombres { get; set; }

        [Display(Name = "Nombre Empleado")]
        public string empe_Nombres { get; set; }

        [Display(Name = "Método de Pago")]
        public string meto_Nombre { get; set; }

        [Display(Name = "Fecha")]
        public DateTime fact_Fecha { get; set; }

        [Display(Name = "Sucursal")]
        public int sucu_Id { get; set; }

        [Display(Name = "Usuario Creación")]
        public string user_UsuCreacion { get; set; }

        [Display(Name = "Usuario Modificación")]
        public string user_UsuModificacion { get; set; }

        [Display(Name = "Fecha Creación")]
        public DateTime fact_FechaCreacion { get; set; }

        [Display(Name = "Fecha Modificación")]
        public DateTime? fact_FechaModificacion { get; set; }
    }
}