// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class VW_tbFacturas_List
    {
        public int fact_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string empe_Nombres { get; set; }
        public string meto_Nombre { get; set; }
        public DateTime fact_Fecha { get; set; }
        public string user_UsuCreacion { get; set; }
        public string user_UsuModificacion { get; set; }
        public DateTime fact_FechaCreacion { get; set; }
        public DateTime fact_FechaModificacion { get; set; }
    }
}