// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Maquillaje.DataAccess.Context;

namespace Maquillaje.DataAccess.Context
{
    public partial class MaquillajeContext
    {
        private MaquillajeContextProcedures _procedures;

        public virtual MaquillajeContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MaquillajeContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public MaquillajeContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MaquillajeContextProcedures
    {
        private readonly MaquillajeContext _context;

        public MaquillajeContextProcedures(MaquillajeContext context)
        {
            _context = context;
        }

        public virtual async Task<List<UDP_maqu_tbCategorias_ListResult>> UDP_maqu_tbCategorias_ListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UDP_maqu_tbCategorias_ListResult>("EXEC @returnValue = [dbo].[UDP_maqu_tbCategorias_List]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
