// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Maquillaje.DataAccess.Context
{
    public partial class UDP_maqu_tbCategorias_ListResult
    {
        public int cate_Id { get; set; }
        public string cate_Nombre { get; set; }
    }
}
